name: "Suwayomi Server"
version: "1.4.0"
slug: "suwayomi"
description: "Suwayomi Server as a Home Assistant add-on"
url: "https://github.com/Th3ABombs/suwayomi-addon/tree/main/suwayomi"
startup: application
boot: auto
init: false
panel_icon: mdi:book-open-page-variant

arch:
  - amd64
  - aarch64

map:
  - type: share
    read_only: false

ports:
  4567/tcp: 4567
ports_description:
  4567/tcp: "Suwayomi Web UI"

webui: "http://[HOST]:[PORT:4567]"

options:
  tz: "Europe/Rome"
  update_interval: 12
  update_manga_info: false
  update_exclude_started: false
  update_exclude_completed: true
  web_ui_update_interval: 0
  auto_download_chapters: true
  auto_download_exclude_unread: true
  auto_download_new_chapters_limit: 5
  auto_download_ignore_reuploads: true
  download_as_cbz: true

schema:
  tz: str
  update_interval: "float(0,168)"
  update_manga_info: bool
  update_exclude_started: bool
  update_exclude_completed: bool
  web_ui_update_interval: "int(0,23)"
  auto_download_chapters: bool
  auto_download_exclude_unread: bool
  auto_download_new_chapters_limit: "int(0,9999)"
  auto_download_ignore_reuploads: bool
  download_as_cbz: bool
