name: "Suwayomi Server"
version: "1.2.0"
slug: "suwayomi"
description: "Suwayomi Server as a Home Assistant add-on"
url: "https://github.com/Th3ABombs/suwayomi-addon/tree/main/suwayomi"
startup: application
boot: auto
init: false
panel_icon: mdi:book-open-page-variant

arch:
  - amd64
  - aarch64

ports:
  4567/tcp: 4567
ports_description:
  4567/tcp: "Suwayomi Web UI"

webui: "http://[HOST]:[PORT:4567]"

options:
  tz: "Europe/Rome"

schema:
  tz: str
